### ISSUE TITLE
Accidental PR

### ISSUE THREAD

**Issue by csakai** [MichaelAng/dnd#2]
Looks like when I pushed to characterCreation, it set up a pull request for master. not what I meant to do.

**Comment by MichaelAng** [comment]
it is ok. it didnt break anything did it?

**Comment by csakai** [comment]
Nah, I don't think so

## 

Chris Sakai
Lead Developer at Jozii
www.jozii.com
CS.Chris.Sakai@gmail.com
(718) 974-6030

**Comment by MichaelAng** [comment]
Ok good to go
